-- AlterTable
ALTER TABLE "ApprovalRequest" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "BankAccount" ALTER COLUMN "balance" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "BankTransaction" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "divergence" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "CashEntry" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "CashSession" ALTER COLUMN "openingAmount" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "closingAmount" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "creditLimit" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "balance" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "Document" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "Employee" ALTER COLUMN "salary" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "FinancialEntry" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "FiscalNote" ALTER COLUMN "total" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "NoteItem" ALTER COLUMN "qty" SET DATA TYPE DECIMAL(14,3),
ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "PayrollEntry" ALTER COLUMN "baseSalary" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "fgts" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "inss" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "netPay" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "vacationDue" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "price" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "cost" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "stockQty" SET DATA TYPE DECIMAL(14,3),
ALTER COLUMN "minStock" SET DATA TYPE DECIMAL(14,3);

-- AlterTable
ALTER TABLE "StockMovement" ALTER COLUMN "qty" SET DATA TYPE DECIMAL(14,3);

-- AlterTable
ALTER TABLE "TaxObligation" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "baseRevenue" SET DATA TYPE DECIMAL(14,2);
